### ISSUE TITLE
balancer-exchange vs. balancer-frontend

### ISSUE THREAD

**Issue by memoriesadrift** [balancer-labs/balancer-frontend#30]
Hi there,
I've been looking through the balancer repositories and tried running them locally, too. I've recently noticed that there are two repositories for the front-end, which seems rather peculiar.
How does this repo relate to https://github.com/balancer-labs/balancer-exchange? Are they equivalent? If yes, is the balancer-exchange repo being deprecated? Is this repo stable? 
Thank you in advance for your response!

**Comment by Destiner** [comment]
Hey.

This is the up-to-date repo for the exchange frontend. The other one (`balancer-exchange`) is being deprecated.
